IF(DEFINED ENV{LIBSVMLIN_DIR})
	SET(LIBSVMLIN_ROOT_DIR "$ENV{LIBSVMLIN_DIR}")
ELSE()
	IF(EXISTS "${CMAKE_CURRENT_LIST_DIR}/liblinear-1.91")
		SET(LIBSVMLIN_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}/liblinear-1.91")
	ENDIF()
ENDIF()

SET(LIBSVMLIN_LIB_DIR "${LIBSVMLIN_ROOT_DIR}")
SET(LIBSVMLIN_INCLUDE_DIR "${LIBSVMLIN_ROOT_DIR}")
SET(LIBSVMLIN_INCLUDES 
	"${LIBSVMLIN_INCLUDE_DIR}/blas/blas.h"
	"${LIBSVMLIN_INCLUDE_DIR}/blas/blasp.h"
	"${LIBSVMLIN_INCLUDE_DIR}/linear.h"
	"${LIBSVMLIN_INCLUDE_DIR}/tron.h")

IF(UNIX)
	IF(EXISTS "${LIBSVMLIN_LIB_DIR}/libLiblinear.a")
	   SET(LIBSVMLIN_LIBRARIES "${LIBSVMLIN_LIB_DIR}/libLiblinear.a")
   	ELSE()
	   SET(LIBSVMLIN_LIBRARIES "${LIBSVMLIN_LIB_DIR}/build/libLiblinear.a")
	ENDIF()
ELSE()
	IF(EXISTS "${LIBSVMLIN_LIB_DIR}/Release/Liblinear.lib")
	   SET(LIBSVMLIN_LIBRARIES "${LIBSVMLIN_LIB_DIR}/Release/Liblinear.lib")
   	ELSE()
	   SET(LIBSVMLIN_LIBRARIES "${LIBSVMLIN_LIB_DIR}/build/Release/Liblinear.lib")
	   
	ENDIF()
ENDIF()


####################   Macro   #######################
MACRO(CHECK_FILES _FILES _DIR)
	SET(_MISSING_FILES)
	FOREACH(_FILE ${${_FILES}})
		IF(NOT EXISTS "${_FILE}")
			SET(LIBSVMLIN_FOUND NO)
			get_filename_component(_FILE ${_FILE} NAME)
			SET(_MISSING_FILES "${_MISSING_FILES}${_FILE}, ")
		ENDIF()
	ENDFOREACH()
	IF(_MISSING_FILES)
		MESSAGE(STATUS "In folder \"${${_DIR}}\" not found files: ${_MISSING_FILES}")
		SET(LIBSVMLIN_FOUND NO)
	ENDIF()
ENDMACRO(CHECK_FILES)

MACRO(CHECK_DIR _DIR)    
	IF(NOT EXISTS "${${_DIR}}")
		MESSAGE(STATUS "Folder \"${${_DIR}}\" not found.")
		SET(LIBSVMLIN_FOUND NO)
	ENDIF()
ENDMACRO(CHECK_DIR)

##################### Checking #######################
MESSAGE(STATUS "Searching LIBSVMLIN.")
SET(LIBSVMLIN_FOUND YES)

CHECK_DIR(LIBSVMLIN_ROOT_DIR)
IF(LIBSVMLIN_FOUND)
	CHECK_DIR(LIBSVMLIN_LIB_DIR)
	CHECK_DIR(LIBSVMLIN_INCLUDE_DIR)
	
	IF(LIBSVMLIN_FOUND)
		CHECK_FILES(LIBSVMLIN_LIBRARIES LIBSVMLIN_LIB_DIR)
		CHECK_FILES(LIBSVMLIN_INCLUDES LIBSVMLIN_INCLUDE_DIR)
	ENDIF()
ENDIF()

MESSAGE(STATUS "LIBSVMLIN_FOUND - ${LIBSVMLIN_FOUND}.")
